const StateList = [
  {
    id: 1,
    StateName: "New Delhi",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 600000,
        RoadTax: 4,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 600000,
        RoadTax: 5,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: "Diesel",
        Min: 600001,
        Max: 1000000,
        RoadTax: 8.75,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: Infinity,
        RoadTax: 12.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 2,
    StateName: "Uttar Pradesh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 1000000,
        RoadTax: 8,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 3,
    StateName: "Haryana",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 600000,
        RoadTax: 5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 2000000,
        RoadTax: 8,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 4,
    StateName: "Maharashtra",
    FactorType: "Price",
    Factor: [
      {
        FuelType: "CNG",
        Min: 0,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: ["Petrol", "Hybrid"],
        Min: 0,
        Max: 1000000,
        RoadTax: 11,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 1000000,
        RoadTax: 13,
      },
      {
        FuelType: ["Petrol", "Hybrid"],
        Min: 1000001,
        Max: 2000000,
        RoadTax: 12,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: 2000000,
        RoadTax: 14,
      },
      {
        FuelType: ["Petrol", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 13,
      },
      {
        FuelType: "CNG",
        Min: 0,
        Max: Infinity,
        RoadTax: 7,
      },
      {
        FuelType: "Diesel",
        Min: 2000001,
        Max: Infinity,
        RoadTax: 15,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 5,
    StateName: "Andhra Pradesh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 13,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 14,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 2000000,
        RoadTax: 17,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 18,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: 1000000,
        RoadTax: 11,
      },
      {
        FuelType: "Electric",
        Min: 1000001,
        Max: 2000000,
        RoadTax: 14,
      },
      {
        FuelType: "Electric",
        Min: 2000001,
        Max: Infinity,
        RoadTax: 15,
      },
    ],
  },
  {
    id: 6,
    StateName: "Telangana",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 13,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 14,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 2000000,
        RoadTax: 17,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 18,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: 1000000,
        RoadTax: 11,
      },
      {
        FuelType: "Electric",
        Min: 1000001,
        Max: 2000000,
        RoadTax: 14,
      },
      {
        FuelType: "Electric",
        Min: 2000001,
        Max: Infinity,
        RoadTax: 15,
      },
    ],
  },
  {
    id: 7,
    StateName: "Kerala",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 9,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 11,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 1500000,
        RoadTax: 13,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: 2000000,
        RoadTax: 16,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 21,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 8,
    StateName: "Karnataka",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 13,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 14,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 2000000,
        RoadTax: 17,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 18,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 9,
    StateName: "Odisha",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 6,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 8,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 10,
    StateName: "Tamil Nadu",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 12,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 13,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 2000000,
        RoadTax: 18,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 20,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 11,
    StateName: "West Bengal",
    FactorType: "Displacement",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 5.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 12,
    StateName: "Chandigarh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 1500000,
        RoadTax: 10,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: Infinity,
        RoadTax: 12,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 13,
    StateName: "Punjab",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 1500000,
        RoadTax: 10,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: Infinity,
        RoadTax: 12,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 14,
    StateName: "Gujarat",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 6,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 15,
    StateName: "Rajasthan",
    FactorType: "Displacement",
    Factor: [
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 800,
        RoadTax: 6,
      },
      {
        FuelType: ["Petrol", "CNG"],
        Min: 801,
        Max: 1200,
        RoadTax: 9,
      },
      {
        FuelType: ["Petrol", "CNG"],
        Min: 1201,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: ["Diesel"],
        Min: 0,
        Max: 1200,
        RoadTax: 11,
      },
      {
        FuelType: ["Diesel"],
        Min: 1201,
        Max: Infinity,
        RoadTax: 12,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 16,
    StateName: "Bihar",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 800000,
        RoadTax: 9,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 800001,
        Max: 1500000,
        RoadTax: 10,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: Infinity,
        RoadTax: 12,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 17,
    StateName: "Jharkhand",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 700000,
        RoadTax: 7,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 700001,
        Max: Infinity,
        RoadTax: 9,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 18,
    StateName: "Uttarakhand",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 8,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 9,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 19,
    StateName: "Himachal Pradesh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 1500000,
        RoadTax: 6,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: Infinity,
        RoadTax: 7,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 20,
    StateName: "Puducherry",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 1000000,
        RoadTax: 6,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 7,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 21,
    StateName: "Madhya Pradesh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 1000000,
        RoadTax: 8,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 2000000,
        RoadTax: 10,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 14,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 1000000,
        RoadTax: 10,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: 2000000,
        RoadTax: 12,
      },
      {
        FuelType: "Diesel",
        Min: 2000001,
        Max: Infinity,
        RoadTax: 16,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 4,
      },
    ],
  },
  {
    id: 22,
    StateName: "Chhattisgarh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 500000,
        RoadTax: 8,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: Infinity,
        RoadTax: 9,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 23,
    StateName: "Jammu and Kashmir",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 9,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 24,
    StateName: "Assam",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 400000,
        RoadTax: 5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 400001,
        Max: 600000,
        RoadTax: 6,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1200000,
        RoadTax: 7,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1200001,
        Max: 1500000,
        RoadTax: 7.5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: 2000000,
        RoadTax: 9,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 12,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 25,
    StateName: "Goa",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Petrol", "Diesel", "CNG"],
        Min: 0,
        Max: 600000,
        RoadTax: 9,
      },
      {
        FuelType: ["Petrol", "Diesel", "CNG"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 11,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 12,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 26,
    StateName: "Arunachal Pradesh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 300000,
        RoadTax: 2.5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 300001,
        Max: 500000,
        RoadTax: 2.7,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 500001,
        Max: 1000000,
        RoadTax: 3,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 1500000,
        RoadTax: 3.5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: 1800000,
        RoadTax: 4,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1800001,
        Max: 2000000,
        RoadTax: 4.5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000001,
        Max: Infinity,
        RoadTax: 6.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 27,
    StateName: "Manipur",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 300000,
        RoadTax: 3,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 300001,
        Max: 600000,
        RoadTax: 4,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 5,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: 1500000,
        RoadTax: 6,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1500001,
        Max: 2000000,
        RoadTax: 7,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 2000000,
        Max: Infinity,
        RoadTax: 8,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 28,
    StateName: "Mizoram",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 6,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 6,
      },
    ],
  },
  {
    id: 29,
    StateName: "Nagaland",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 4,
      },
    ],
  },
  {
    id: 30,
    StateName: "Sikkim",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 3,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 1,
      },
    ],
  },
  {
    id: 31,
    StateName: "Tripura",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1,
        Max: 600000,
        RoadTax: 6,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 8,
      },
    ],
  },
  {
    id: 32,
    StateName: "Andaman and Nicobar",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Diesel", "Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: Infinity,
        RoadTax: 9.2,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 9.2,
      },
    ],
  },
  {
    id: 33,
    StateName: "Dadra and Nagar Haveli and Daman and Diu",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 600000,
        RoadTax: 4,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 600000,
        RoadTax: 5,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: "Diesel",
        Min: 600001,
        Max: 1000000,
        RoadTax: 8.75,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: Infinity,
        RoadTax: 12.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 34,
    StateName: "Ladakh",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 600000,
        RoadTax: 4,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 600000,
        RoadTax: 5,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: "Diesel",
        Min: 600001,
        Max: 1000000,
        RoadTax: 8.75,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: Infinity,
        RoadTax: 12.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 35,
    StateName: "Lakshadweep",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 600000,
        RoadTax: 4,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 600000,
        RoadTax: 5,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: "Diesel",
        Min: 600001,
        Max: 1000000,
        RoadTax: 8.75,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: Infinity,
        RoadTax: 12.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
  {
    id: 36,
    StateName: "Meghalaya",
    FactorType: "Price",
    Factor: [
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 0,
        Max: 600000,
        RoadTax: 4,
      },
      {
        FuelType: "Diesel",
        Min: 0,
        Max: 600000,
        RoadTax: 5,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 600001,
        Max: 1000000,
        RoadTax: 7,
      },
      {
        FuelType: "Diesel",
        Min: 600001,
        Max: 1000000,
        RoadTax: 8.75,
      },
      {
        FuelType: ["Petrol", "CNG", "Hybrid"],
        Min: 1000001,
        Max: Infinity,
        RoadTax: 10,
      },
      {
        FuelType: "Diesel",
        Min: 1000001,
        Max: Infinity,
        RoadTax: 12.5,
      },
      {
        FuelType: "Electric",
        Min: 0,
        Max: Infinity,
        RoadTax: 0,
      },
    ],
  },
];

const insuranceList = [
  {
    Min: 0,
    Max: 500000,
    insurancePercentage: "5.8",
  },
  {
    Min: 500001,
    Max: 1000000,
    insurancePercentage: "5.5",
  },
  {
    Min: 1000001,
    Max: 1500000,
    insurancePercentage: "5.3",
  },
  {
    Min: 1500001,
    Max: 2500000,
    insurancePercentage: "5",
  },
  {
    Min: 2500001,
    Max: 3500000,
    insurancePercentage: "4.8",
  },
  {
    Min: 3500001,
    Max: 4500000,
    insurancePercentage: "4.5",
  },
  {
    Min: 4500001,
    Max: 6000000,
    insurancePercentage: "4.3",
  },
  {
    Min: 6000001,
    Max: 8000000,
    insurancePercentage: "4.1",
  },
  {
    Min: 8000001,
    Max: Infinity,
    insurancePercentage: "3.9",
  },
];

module.exports = { StateList , insuranceList };
